# Generated by Django 6.1.1 on 2026-09-30 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('anexo', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImpresoraRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_inventario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de impresora',
                'verbose_name_plural': 'Registros de impresoras',
                'db_table': 'registro_impresoras',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pantalla_numero', models.PositiveSmallIntegerField(default=1)),
                ('hdmi', models.BooleanField(default=False)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_inventario', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('numero_inventario', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tiene_monitor', models.BooleanField(default=False)),
                ('tiene_impresora', models.BooleanField(default=False)),
                ('numero_serie_impresora', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_inventario_impresora', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.disco')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.marcaequipo')),
                ('marca_impresora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.marcaimpresora')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.modeloequipo')),
                ('modelo_impresora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.modeloimpresora')),
                ('procesador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.procesador')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.memoriaram')),
                ('sistema_operativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.sistemaoperativo')),
            ],
            options={
                'verbose_name': 'Registro de equipo',
                'verbose_name_plural': 'Registros de equipos',
                'db_table': 'registro_equipos',
            },
        ),
    ]
