# Generated by Django 6.1.1 on 2026-09-25 13:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('anexo', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'El anexo debe ser un número de 4 dígitos.')])),
            ],
        ),
        migrations.CreateModel(
            name='ImpresoraRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pantalla_numero', models.PositiveSmallIntegerField(default=1)),
                ('hdmi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('numero_inventario', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tiene_monitor', models.BooleanField()),
                ('tiene_impresora', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.disco')),
                ('procesador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.procesador')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.memoriaram')),
                ('sistema_operativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.sistemaoperativo')),
            ],
        ),
    ]
