# Generated by Django 6.1.1 on 2026-09-30 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('existencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.tipoequipo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.cargo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.departamento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.direccion'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='existencias.funcionario'),
        ),
        migrations.AddField(
            model_name='impresoraregistro',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.departamento'),
        ),
        migrations.AddField(
            model_name='impresoraregistro',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.direccion'),
        ),
        migrations.AddField(
            model_name='impresoraregistro',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.estadoimpresora'),
        ),
        migrations.AddField(
            model_name='impresoraregistro',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.marcaimpresora'),
        ),
        migrations.AddField(
            model_name='impresoraregistro',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.modeloimpresora'),
        ),
        migrations.AddField(
            model_name='impresoraregistro',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impresoras_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monitor',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitores', to='existencias.equipo'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.marcamonitor'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.modelomonitor'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='pulgadas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.pulgadasmonitor'),
        ),
    ]
